# Site Settings
title: Negar Kamali
description: "Negar Kamali â€” CS PhD student at Northwestern studying AI-generated media detection, human-AI interaction, and AI alignment"
url: https://negarkamali.github.io
baseurl: ""
logo: /images/berlin.jpg
email: negar.kamali@u.northwestern.edu
color-scheme: auto
show_downloads: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist
